version: '3.5'

services:
  db:
    image: postgres
    container_name: dataforgood_postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    container_name: dataforgood_web
#     command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db:
    name: dataforgood_db
